### ISSUE TITLE
[BUG] "unrecognized arguments: --new" but only when actually executing backup

### ISSUE THREAD

**Issue by ccazabon** [rdiff-backup/rdiff-backup#1009]
## Bug summary

Using latest git master installed in a local virtualenv to try to debug something, a new-style backup command gives the error:
`rdiff-backup: error: unrecognized arguments: --new`

Invocation of `rdiff-backup --new --help` does not give the error, showing the correct help including documenting the --new option.

I ran into this while trying to update my backup scripts to use the new-style arguments, and eliminate the deprecation warning.  Not positive it's a bug, but this minimal test case doesn't look like it has a lot of room for user error.

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 201
    max: 201
    min: 201
  argv:
  - [...path...]/software/rdiff-backup/.venv/bin/rdiff-backup
  - info
  parsed:
    action: info
    api_version: null
    chars_to_quote: null
    current_time: null
    force: false
    fsync: true
    null_separator: false
    parsable_output: false
    remote_schema: null
    remote_tempdir: null
    ssh_compression: true
    tempdir: null
    terminal_verbosity: null
    use_compatible_timestamps: false
    verbosity: 3
  version: 2.6.1.dev22+g45b85ea
python:
  executable: [...path...]/software/rdiff-backup/.venv/bin/python
  name: cpython
  version: 3.11.9
system:
  fs_encoding: utf-8
  platform: Linux-6.8.10-x86_64-with-glibc2.36
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

Minimal test case:
```
$ rdiff-backup -v 9 --new backup ./back-source ./back-dest
```

## What happened and what did you expect?

Expected: test backup from one local dir to the other.

Actual:
```
$ rdiff-backup --new -v 9 backup back-source back-dest
usage: rdiff-backup [-h] [--api-version API_VERSION]
                    [--current-time CURRENT_TIME] [--force]
                    [--fsync | --no-fsync] [--null-separator]
                    [--chars-to-quote CHARS] [--parsable-output]
                    [--remote-schema REMOTE_SCHEMA]
                    [--remote-tempdir DIR_PATH]
                    [--ssh-compression | --no-ssh-compression]
                    [--tempdir DIR_PATH]
                    [--terminal-verbosity {0,1,2,3,4,5,6,7,8,9}]
                    [--use-compatible-timestamps] [-v {0,1,2,3,4,5,6,7,8,9}]
                    [-V]
                    {backup,calculate,compare,complete,info,list,regress,remove,restore,server,test,verify}
                    ...
rdiff-backup: error: unrecognized arguments: --new
```

## More information

I've run this with PYTHONVERBOSE set and verified that it's not loading any files from the Debian-packaged rdiff-backup, only from the installed version in the virtualenv.
