### ISSUE TITLE
Very slow first backup over SSH

### ISSUE THREAD

**Issue by Michal-Zacek** [rdiff-backup/rdiff-backup#1048]
## What is it about?

First(full) backup over ssh is really slow even if I test it on localhost on my PC. 

## Version, Python, Operating System
Test PC:
AMD Ryzen 5 7600X 6-Core Processor
RAM: 64GB
HDD: NVME Samsung SSD 980 PRO 1TB
Linux Mint 22
Filesystem: ext4

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.12.3
system:
  fs_encoding: utf-8
  platform: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
...

```

## rdiff-backup call
I tested it on  a 50GB "tmp" directory with 100 000 files and 11 000 dirs.

### First simple local disk2disk backup, speed: 300MB/s:

time rdiff-backup tmp/ rdiff/tmp/
real	2m46,221s
user	0m47,718s
sys	0m48,002s

### then ssh on localhost backup, speed 50MB/s:

time rdiff-backup zacekm@127.0.0.1::/mnt/data/zacekm/tmp/  rdiff/tmp-ssh/
real	16m31,918s
user	2m31,979s
sys	1m5,531s

### and finnaly rsync over ssh, speed 460MB/s:

time rsync -raAX --stats   zacekm@127.0.0.1:/mnt/data/zacekm/tmp/  rdiff/tmp-rsync/
real	1m47,266s
user	0m43,481s
sys	0m51,800s

As you can see, rdiff-backup over ssh is 9x slower than rsync over ssh. Is this to be expected?  When I try to back up data between servers the speed is even slower, about 10MB/s on a 25Gb/s network.

Regards.
