### ISSUE TITLE
[ENH] don't return a warning when there are no increments to remove

### ISSUE THREAD

**Issue by TimothyPMann** [rdiff-backup/rdiff-backup#1071]
## Bug summary

I don't need a warning if I ask to remove old increments and there are no increments that old. A note is okay, but a note and two warnings is rather excessive. If some people need this warning for some reason, perhaps there could be an option to suppress it. I'd use that so that my cron job doesn't send me an email every day full of useless warnings.

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.12.3
system:
  fs_encoding: utf-8
  platform: Linux-5.15.0-140-lowlatency-x86_64-with-glibc2.39
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
sudo rdiff-backup --api-version 201 remove increments --older-than 1Y /extra/backup/boot
```

## What happened and what did you expect?

$ sudo rdiff-backup --api-version 201 remove increments --older-than 1Y /extra/backup/boot
NOTE:    No increments older than Sat May 25 14:56:07 2024 found, exiting.
WARNING: No increment is older than '1Y'
WARNING: Action remove emitted warnings, see previous messages for details

I would have expected no warnings, as the NOTE is enough.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.
