### ISSUE TITLE
Automate creation of binaries in Travis CICD pipeline

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#188]
To automate the creation of release as mush as possible, we need to add the creation of binaries files directly in travis and manage to push them as release into github when a tag is generated.
To complete this task, let focus on generating binaries packages as we did for 1.4.0b0: tag.gz for Linux, source distribution, wheel package.

**Comment by ericzolf** [comment]
Do we want to have this for the release/milestone 2.0.0? Are we able to do this in acceptable time?

**Comment by ardovm** [comment]
I would be glad to help, but you should please give me some indications, like a RTFM pointer or a working example to replicate.

**Comment by ikus060** [comment]
@ardovm 
This need to be done in few steps.
First is generating the wheel packages for linux:: `python setup bdist_wheel`
Then we need to "repair" them for pypi: `auditwheel repair <.whl>`
Finnaly you must push it to github. That I don't know how.

For Windows, I think you did everything already.
You must call pyinstaller...

**Comment by ericzolf** [comment]
I started a bit to work on deployment with Travis CI but didn't come too far. Anyway, something like this should be required:

```yaml
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  # uncomment for draft releases
  draft: true
  # uncomment in productive mode
  # on:
  #  tags: true
```
