### ISSUE TITLE
[BUG] The system cannot find the path specified: b'B:/rdiff/rdiff-backup-data/increments'

### ISSUE THREAD

**Issue by dtxl** [rdiff-backup/rdiff-backup#558]
## Bug summary

Made two backup runs with

rdiff-backup.exe -v0 --force backup --exclude C:/Users/user/AppData --exclude C:/Users/user/Downloads C:/Users/user B:/rdiff

which stopped with the error 

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: b'B:/rdiff/rdiff-backup-data/increments/.../longfilename.pdfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
[15252] Failed to execute script rdiff-backup

where the file to backup has the filename "longfilename.pdf". 
Then the second backup run stops with the error

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 95, in _main_run
  File "rdiffbackup\actions\backup.py", line 129, in run
  File "rdiffbackup\locations\repository.py", line 100, in needs_regress
  File "rdiff_backup\FilenameMapping.py", line 89, in listdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: b'B:/rdiff/rdiff-backup-data/increments'
[27988] Failed to execute script rdiff-backup

## Version, Python, Operating System
Alpha Release v2.1.0a1 - fix Windows 64 bits, W10 LTCS 1809

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - rdiff-backup
  - info
  version: 2.1.0a1
python:
  executable: C:\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.17763-SP0
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup.exe -v0 --force backup --exclude C:/Users/user/AppData --exclude C:/Users/user/Downloads C:/Users/user B:/rdiff
```

## What happened and what did you expect?

the first run stopped after the error cf. above and the second run then totally failed.

## More information

I repeated the action with the option `-v9`, but the output is too long.
