### ISSUE TITLE
[BUG] Better error reporting when failing to authenticate via plink on Windows

### ISSUE THREAD

**Issue by rstarkov** [rdiff-backup/rdiff-backup#564]
## Bug summary

When plink fails to authenticate on Windows, rdiff-backup exits with a very unhelpful message.

On 2.0.5, it exited with a "Integer overflow while attempting ..." message.

On 2.1.0a1 it exits with a MemoryError in "rdiff_backup\connection.py", line 273, in _read

## Version, Python, Operating System

```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - C:\Path\To\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: C:\Path\To\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.18362-SP0
```

## rdiff-backup call

I generally call it with a schema like: `C:\Path\To\PuTTY\plink.exe %s -l Roman -C C:\Remote\rdiff-backup.exe --server` (or `server` for 2.1)
