### ISSUE TITLE
[BUG] `remove increments --older-than` returns an error when there is no increment to remove in v2.1.0a1

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#616]
## Bug summary

Using v2.1.0a1, calling *with the new or old interface*, removing increments with the `--older-than` option returns 1 (error) if there is no increment old enough to be removed.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - c:\Program Files\rdiff-backup\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: c:\Program Files\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
...
```

## rdiff-backup call

```
"C:\Program Files\rdiff-backup-v210a1\rdiff-backup.exe" remove increments --older-than 3Y D:\  # returns 1
"C:\Program Files\rdiff-backup-v205\rdiff-backup.exe" --remove-older-than 3Y D:\  # returns 0
```

## What happened and what did you expect?

`rdiff-backup` v2.1.0a1 returns `1` while v2.0.5 returns `0`.

As a user, I would expect the command to return `0` (success) if it can access the backup directory and list its increments, meaning it runs without unexpected error, even if there is no matching increment to remove and it terminates without removing any.
This expectation seems consistent with how the `man` entry describes `rdiff-backup` return value:
````
If rdiff-backup finishes successfully, the exit status will be  0.   If
       there  is  an unrecoverable (critical) error, it will be non-zero (usu-
       ally 1, but don't depend on this  specific  value).   When  setting  up
       rdiff-backup  to  run  automatically (as from cron(8) or similar) it is
       probably a good idea to check the exit code.
````

Note that this "no matching increment found" case is different from the "specified increment not found" case of removing a given specific increment, where it does make sense to consider it an error if the increment doesn't exist.

## More information

My use case is running `rdiff-backup` in automated scripts and performing cleanup of old backups automatically.
The current behavior makes it impossible to check the exit code for potential execution error (e.g. "backup repository unaccessible") as suggested by the manual in such a use case.
