### ISSUE TITLE
Error specifying both base directory and a globbing pattern in an exclude directive in Windows

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#620]
Not sure it's a bug, it may be usage problem, but why does this command work fine:
```
rdiff-backup.exe backup --exclude-symbolic-links --exclude '**/Users/*/AppData/Roaming/Mozilla/Firefox/' --include 'C:/Users/TheUser' --exclude 'C:/' C:/ D:/
```
while this similar one fails with the following error:
```
rdiff-backup.exe backup --exclude-symbolic-links --exclude 'C:/Users/*/AppData/Roaming/Mozilla/Firefox/' --include 'C:/Users/TheUser' --exclude 'C:/' C:/ D:/

Fatal Error: Fatal Error: The file specification
At line:1 char:1
+ rdiff-backup.exe backup --exclude-symbolic-links --exclude 'C:/Users/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (2021-08-27 22:1...e specification:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    'b'C:/Users/*/AppData/Roaming/Mozilla/Firefox/''
cannot match any files in the base directory
    'b'C:/''
Useful file specifications begin with the base directory or some
pattern (such as '**') which matches the base directory.
```
?

I tried executing the command from the context of the base directory (`cd C:\`), and using escaping backslashes as suggested in the Windows README but it didn't make a difference.

`rdiff-backup.exe backup --exclude-symbolic-links --exclude 'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/' --include 'C:/Users/TheUser' --exclude 'C:/' C:/ D:/` works fine as well so it seems to be a problem when the base directory is specified in a pattern containing globbing characters.

Is this syntax supposed not to be acceptable?

-----

Environment:
```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - C:\Program Files\rdiff-backup\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: C:\Program Files\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
...
```
