### ISSUE TITLE
--exclude not behaving as expected on new CLI (also issues on Windows)

### ISSUE THREAD

**Issue by lostromb** [rdiff-backup/rdiff-backup#679]
## Bug summary

I am trying to use the new CLI on Windows to run a command in the form of: `rdiff-backup --new --exclude "D:\Share\Exclude" backup "D:\Share" "E:\Backup"`. However, the command fails because the `--exclude` argument is not in the correct order, it seems to expect an action name there instead. This doesn't seem to line up with the expected order of arguments given in `rdiff-backup --new backup -h`.

Putting it at the end seems to work.
`rdiff-backup --new backup "D:\Share" "E:\Backup" --exclude "D:/Share/Exclude"`

Also, semi-related bug, on Windows command line, backslashes seem fine when specifying most paths but they don't work with the `--exclude` parameter, so I have to change them to forward slashes. Namely, `--exclude "C:\Share\Source"` does not work, but `--exclude "C:/Share/Source"` does. Not sure if this is because that string is interpreted as a glob instead of an explicit path.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - rdiff-backup
  - info
  version: 2.1.0a1
python:
  executable: C:\Program Files\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --new --exclude "D:\Share\Exclude" --terminal-verbosity 5 --tempdir "C:\rdiff-backup\tmp" backup "D:\Share" "E:/Backup"
```

## What happened and what did you expect?

```
rdiff-backup: error: argument action: invalid choice: 'E:/Backup' (choose from 'regress', 'restore', 'remove', 'compare', 'info', 'backup', 'server', 'verify', 'test', 'list', 'calculate')
```

## More information

Adding -v9 does not generate any additional output, unfortunately.
