### ISSUE TITLE
[BUG] --no-ssh-compression and --null-separator options are not recognized

### ISSUE THREAD

**Issue by rknichols** [rdiff-backup/rdiff-backup#739]
## Bug summary

In the new command line interface, the --no-ssh-compression and --null-separator options are not recognized.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
exec:
  api_version: {actual: 0, default: 200, max: 201, min: 200}
  argv: [/usr/bin/rdiff-backup, info]
  parsed: null
  version: 2.1.2b1
python: {executable: /usr/bin/python3, name: cpython, version: 3.6.8}
system: {fs_encoding: utf-8, platform: Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-centos-8.6-Green_Obsidian}
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup backup --no-ssh-compression --null-separator rback /var/tmp/test-archive
```

## What happened and what did you expect?

usage: rdiff-backup [-h] [--api-version API_VERSION]
                    [--current-time CURRENT_TIME] [--force] [--fsync]
                    [--null-separator] [--new] [--chars-to-quote CHARS]
                    [--parsable-output] [--remote-schema REMOTE_SCHEMA]
                    [--remote-tempdir DIR_PATH] [--ssh-compression]
                    [--tempdir DIR_PATH]
                    [--terminal-verbosity {0,1,2,3,4,5,6,7,8,9}]
                    [--use-compatible-timestamps] [-v {0,1,2,3,4,5,6,7,8,9}]
                    [-V]
                    {backup,calculate,compare,info,list,regress,remove,restore,server,test,verify}
                    ...
rdiff-backup: error: unrecognized arguments: --no-ssh-compression --null-separator

## More information

Running with "-v9" yields the same output as above.
