### ISSUE TITLE
[RFE] Make "verify" detect missing enpty directories in the mirror

### ISSUE THREAD

**Issue by rknichols** [rdiff-backup/rdiff-backup#783]
## Bug summary

The "verify" action does not complain when an empty directory is present in the mirror_metadata file but missing in the mirror. This situation will go undetected until some future time when that directory is deleted in the source, which will cause the next backup session to fail mysteriously.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
exec:
  api_version: {actual: 0, default: 200, max: 201, min: 200}
  argv: [/usr/bin/rdiff-backup, info]
  parsed: null
  version: 2.1.3b3
python: {executable: /usr/bin/python3, name: cpython, version: 3.6.8}
system: {fs_encoding: utf-8, platform: Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-centos-8.6-Green_Obsidian}
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup verify /media/sysbk/lenovo-F36x
```

## What happened and what did you expect?

Got "Every file verified successfully", expected a complaint about missing directory in the mirror.

## More information

Example error message when directory /usr/lib/modules/5.19.12-200.fc36.x86_64/extra is missing in the mirror and was deleted just prior to this backup session:

rdiff-backup --no-ssh-compression backup \
	     --exclude-sockets \
	     --exclude-globbing-filelist ~/rback/exclude-F36 \
	     --exclude-globbing-filelist ~/rback/histfiles-F36 \
	     --preserve-numerical-ids \
	     /mnt/F36 /media/sysbk/lenovo-F36x

Exception 'Either diff '<RORPath/140364064494144:
    Index=('usr', 'lib', 'modules', '5.19.12-200.fc36.x86_64', 'extra')
    Data={'type': None, 'filetype': 'snapshot'}>' or base '<RPath/140364064904528:
    Path=/media/sysbk/lenovo-F36/usr/lib/modules/5.19.12-200.fc36.x86_64/extra
    Index=('usr', 'lib', 'modules', '5.19.12-200.fc36.x86_64', 'extra')
    Connection=LocalConnection
    Data={'type': None}>' must be a directory' raised of class '<class 'AssertionError'>':
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 353, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/Main.py", line 439, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result
