### ISSUE TITLE
[BUG] API 201 backups unchanged hardlinked files with Attempt to rename over same inode

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#816]
## Bug summary

When hardlinked files have different metadata but same content, _and_ with API 201, rdiff-backup fails with a warning of type `WARNING: Attempt to rename over same inode: from path bak/rdiff-backup.tmp.2 to path bak/fileB`

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.0
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.1
system:
  fs_encoding: utf-8
  platform: Linux-6.0.13-300.fc37.x86_64-x86_64-with-glibc2.36
...

```

## rdiff-backup call

Repeater looks like the following:

```
mkdir from
date > from/fileA
ln from/fileA from/fileB
rdiff-backup -v5 --api-version 201 backup from bak
touch from/fileA 
rdiff-backup -v5 --api-version 201 backup from bak
```

## What happened and what did you expect?

```
$ rdiff-backup --api-version 201 backup from bak
NOTE:    Starting backup operation from source path from to destination path
         bak
WARNING: Attempt to rename over same inode: from path bak/rdiff-backup.tmp.2 to
         path bak/fileB
```

The files in the backup repository keep the same inode but the metadata seems to be correct. The warning is unnerving though.

## More information

n/a
