### ISSUE TITLE
[BUG] CloseConnections doesn't wait for child processes to die, losing output

### ISSUE THREAD

**Issue by tecordes** [rdiff-backup/rdiff-backup#819]
## Bug summary

rdiff-backup will exit while the ssh process is still running for .5 to 1.5 seconds.  If I check with ps command at the right time I can see that the ssh command has been taken over by ps 1 as its ppid.

This screws up the capture of the output from my pv pipe-monitoring program at the end of my remote-schema chain.  The output goes to nowhere, since the ppid is now 1.  rdiff-backup never sees/passes on this output.

I've fixed it with a few minor mods to SetConnections.py and connection.py.  Just need to track the child and wait for it to exit.

## Version, Python, Operating System
```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.0
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.10.9
system:
  fs_encoding: utf-8
  platform: Linux-6.0.15-200.fc36.x86_64-x86_64-with-glibc2.35
...
```
## rdiff-backup call

remote-schema ends in:

| /usr/bin/pv -L 200000 -rbWf -i2592000

## What happened and what did you expect?

pv final status output disappears when connection is slow and/or you get unlucky with the race condition.  I expect the final pv status output line to show up so my script can capture it from the rdiff process.

## More information

my fix in brief:

connection.py:
```python
class LowLevelPipeConnection(Connection):
...
    def __init__(self, inpipe, outpipe, process = 0):
        self.process = process

    def _close(self):
        self.outpipe.close()
        self.inpipe.close()
        if self.process!=0: self.process.wait()

class PipeConnection(LowLevelPipeConnection):
    def __init__(self, inpipe, outpipe, conn_number = 0, process = 0 ):
...
	LowLevelPipeConnection.__init__(self, inpipe, outpipe, process)
```
SetConnections.py:
```python
def _init_connection(remote_cmd):
    conn = connection.PipeConnection(stdout, stdin, conn_number, process)
```

Note:
The Python docs on popen says wait could deadlock, but since the rdiff-backup protocol is so precise, I doubt there could ever be remaining data on the pipe at that point.   Otherwise they say to use communicate() but that seems more complicated than what I'm after.  (And Python is not my language of choice nor maximum aptitude.)

I've run this fix since 2019 and never had a problem at all.  I'm tired of manually editing the 2 source files everytime rdiff-backup gets upgraded :-)
