### ISSUE TITLE
[BUG] Typo in Examples in documentation: the option `--print-statistics` should come *after* the `backup` command.

### ISSUE THREAD

**Issue by MarcvdSluys** [rdiff-backup/rdiff-backup#820]
## Bug summary

The option `--print-statistics` should come *after* the `backup` command.  In the Examples, [Section 2](https://rdiff-backup.net/examples.html#backing_up) of the documentation, this is shown as `--print-statistics backup`.  This seems to be the wrong way around, and a typo in the documentation.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/lib/python-exec/python3.10/rdiff-backup
  - info
  parsed: null
  version: 2.2.2
python:
  executable: /usr/bin/python3.10
  name: cpython
  version: 3.10.9
system:
  fs_encoding: utf-8
  platform: Linux-5.10.76-gentoo-r1.008-x86_64-11th_Gen_Intel-R-_Core-TM-_i7-1185G7_@_3.00GHz-with-glibc2.36
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --print-statistics backup --exclude '...' <SRC DIR> <BACKUP DIR>
```

## What happened and what did you expect?

- What happened:
  `rdiff-backup: error: unrecognized arguments: --print-statistics`
- Expected: backup correctly
  - Reason of expectation: the example in the Examples, [Section 2](https://rdiff-backup.net/examples.html#backing_up) of the documentation specifies `--print-statistics backup`
- Solution: `backup --print-statistics` (reversed order) did work as expected.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

- Same as above: `rdiff-backup: error: unrecognized arguments: --print-statistics`
