### ISSUE TITLE
[BUG] Help text for remove increments is incomplete

### ISSUE THREAD

**Issue by slovdahl** [rdiff-backup/rdiff-backup#830]
## Bug summary

Help text for the remove increments action seems to be incomplete, e.g. the `--force` parameter is missing.

## Version, Python, Operating System

```yaml
$ rdiff-backup info
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /home/slovdahl/.local/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.2
python:
  executable: /usr/bin/python3.9
  name: cpython
  version: 3.9.4
system:
  fs_encoding: utf-8
  platform: Linux-4.4.0-1152-raspi2-armv7l-with-glibc2.23
...
```

## rdiff-backup call

```
$ rdiff-backup remove increments --help
usage: rdiff-backup remove increments [-h] --older-than TIME [--size | --no-size] [[USER@]SERVER::]PATH

positional arguments:
  [[USER@]SERVER::]PATH
                        location of repository to remove increments from

optional arguments:
  -h, --help            show this help message and exit
  --older-than TIME     remove increments older than given time
  --size, --no-size     also output size of each increment (might take longer) (default: False)
```

## What happened and what did you expect?

The `--force` parameter is missing:

```
$ rdiff-backup remove increments --older-than 17M /path/to/backup
ERROR: Found 30 relevant increments, dates/times:
Mon Jul 26 02:00:09 2021
Tue Jul 27 02:00:09 2021
Wed Jul 28 02:00:09 2021
Thu Jul 29 02:00:09 2021
Fri Jul 30 02:00:10 2021
Sat Jul 31 02:00:09 2021
Sun Aug  1 02:00:10 2021
Mon Aug  2 02:00:09 2021
Tue Aug  3 02:00:10 2021
Wed Aug  4 02:00:10 2021
Thu Aug  5 02:00:08 2021
Fri Aug  6 02:00:10 2021
Sat Aug  7 02:00:10 2021
Sun Aug  8 02:00:09 2021
Mon Aug  9 02:00:13 2021
Tue Aug 10 02:00:17 2021
Wed Aug 11 02:00:12 2021
Thu Aug 12 02:00:12 2021
Fri Aug 13 02:00:10 2021
Sat Aug 14 02:00:10 2021
Sun Aug 15 02:00:10 2021
Mon Aug 16 02:00:11 2021
Tue Aug 17 02:00:09 2021
Wed Aug 18 02:00:11 2021
Thu Aug 19 02:00:11 2021
Fri Aug 20 02:00:10 2021
Sat Aug 21 02:00:10 2021
Sun Aug 22 02:00:10 2021
Mon Aug 23 02:00:08 2021
Tue Aug 24 02:00:10 2021
If you want to delete multiple increments in this way, use the --force option.
ERROR: Action remove failed on step setup
```

## More information

I'm trying to migrate from the old inteface where I ran:

```
rdiff-backup --remove-older-than 18M --force /path/to/directory/
```

It could also be helpful to list the equivalent for this in the table on https://rdiff-backup.net/migration.html#migration_from_old_to_new_cli.
