### ISSUE TITLE
[BUG] rdiff-backup.1 has incorrect remote-schema example

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#867]
## Bug summary

The example for using the remote-schema in rdiff-backup.1 has `--remote-schema` listed as a sub-option, but it is a global-option.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.4
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.2
system:
  fs_encoding: utf-8
  platform: Linux-6.2.9-200.fc37.x86_64-x86_64-with-glibc2.36
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
man rdiff-backup
```

## What happened and what did you expect?

Example listed is
```
rdiff-backup backup --remote-schema 'cd /usr; {h}' \
                               foo 'rdiff-backup server'::bar
```
but I believe should be
```
rdiff-backup --remote-schema 'cd /usr; {h}' backup \
                               foo 'rdiff-backup server'::bar
```
## More information

Other examples do look to be correct.
