### ISSUE TITLE
[BUG] remove increments --force argument unrecognized

### ISSUE THREAD

**Issue by azemon** [rdiff-backup/rdiff-backup#887]
## Bug summary

The `--force` option is never recognized with `remove increments --older-than`

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.2
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.2
system:
  fs_encoding: utf-8
  platform: Linux-6.2.0-20-generic-x86_64-with-glibc2.37
...
```

## rdiff-backup call

```
tippy:~ $ rdiff-backup remove increments --older-than 60D --force /nfs/dumbo-art/tippy
usage: rdiff-backup [-h] [--api-version API_VERSION] [--current-time CURRENT_TIME] [--force] [--fsync | --no-fsync]
                    [--null-separator] [--new | --no-new] [--chars-to-quote CHARS] [--parsable-output]
                    [--remote-schema REMOTE_SCHEMA] [--remote-tempdir DIR_PATH] [--ssh-compression | --no-ssh-compression]
                    [--tempdir DIR_PATH] [--terminal-verbosity {0,1,2,3,4,5,6,7,8,9}] [--use-compatible-timestamps]
                    [-v {0,1,2,3,4,5,6,7,8,9}] [-V]
                    {backup,calculate,compare,complete,info,list,regress,remove,restore,server,test,verify} ...
rdiff-backup: error: unrecognized arguments: --force
```

## What happened and what did you expect?

I could not remove old increments with the new CLI.

## More information

The old CLI worked properly:

```
tippy:~ $ rdiff-backup --remove-older-than 60D /nfs/dumbo-art/tippy --force
```
