### ISSUE TITLE
[BUG] Getting deprication warning of usage of old command line interface despite already using new

### ISSUE THREAD

**Issue by bufanda** [rdiff-backup/rdiff-backup#899]
## Bug summary

Despite me using already using the new syntax for the command line interface

`rdiff-backup backup source destination` 

I always get the message 
`WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.`

I run the same script on multiple hosts one is an AlmaLinux 9 machine, another one is ubuntu 20.04, but only on this RaspberryPi 2B+ with Debian 10 (buster) is behaving like it. 

On all host rdiff-backup is installed via python pip. 

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/local/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.7.3
system:
  fs_encoding: utf-8
  platform: Linux-5.10.103-v7+-armv7l-with-debian-10.13
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
/usr/local/bin/rdiff-backup backup root@myhost.com::/home /mnt/backupdrive
```

## What happened and what did you expect?

Message appeard
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.

I did expect it do not appear.
