### ISSUE TITLE
[BUG] Version 2.2.6-1 warns about deprecated interface

### ISSUE THREAD

**Issue by rknichols** [rdiff-backup/rdiff-backup#922]
## Bug summary
Version 2.2.6-1 warns "Server will be called with deprecated command line interface..." even for a local operation where no server is involved.

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
exec:
  api_version: {actual: 0, default: 200, max: 201, min: 200}
  argv: [/usr/bin/rdiff-backup, info]
  parsed: null
  version: 2.2.6
python: {executable: /usr/bin/python3.6, name: cpython, version: 3.6.8}
system: {fs_encoding: utf-8, platform: Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-centos-8.8-Green_Obsidian}
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup verify /media/sysbk/omega-3x
```

## What happened and what did you expect?

WARNING: Server will be called with deprecated command line interface to guarantee compatibility. It might lead to a deprecation warning from newer rdiff-backup versions. Use '--api-version 201' (or higher) to avoid it.
