### ISSUE TITLE
How to pause a backup to Continue later

### ISSUE THREAD

**Issue by Golden7ty8** [rdiff-backup/rdiff-backup#923]
## What is it about?

I need be able to pause a backup to continue it later. When I try stuff like closing the command prompt and then running it again, sometimes the program wants to regress the files and sometimes it doesn't.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - rdiff-backup.exe
  - info
  parsed: null
  version: 2.2.6
python:
  executable: S:\S\rdiff-backup\rdiff-backup-2.2.6-64\rdiff-backup.exe
  name: cpython
  version: 3.10.7
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19045-SP0
...
```
