### ISSUE TITLE
[BUG] rdiff-backup chokes on non-ASCII characters in group (and user?) names

### ISSUE THREAD

**Issue by gindos** [rdiff-backup/rdiff-backup#938]
## Bug summary

The program does not work correctly if the snapshot file contains UTF-8 encoded characters.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/local/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/local/bin/python3
  name: cpython
  version: 3.8.6
system:
  fs_encoding: utf-8
  platform: Linux-3.10.105-x86_64-with-glibc2.2.5
...
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
 rdiff-backup --exclude '/**eaDir' -v5 --print-statistics /volume1/images4web/ /volumeUSB2/usbshare/backup_images4web/
```

## What happened and what did you expect?

mirror_metadata.2023-11-03T15:37:00+11:00.snapshot.gz
File .
  Type dir
  ModTime 1698986641
  Uid 0
  Uname root
  Gid 0
  Gname root
  Permissions 0
File screencapture-neptunsale-ru-products-neptunsmart-gsm-2023-11-02-09_24_45.jpg
  Type reg
  Size 141979
  SHA1Digest 9ed392fe52e8c7337acda97c5d8aa1dfb333d5f0
  ModTime 1698877585
  Uid 545260629
  Uname NAME-DOMEN\username
  Gid 545260033
  Gname NAME-DOMEN\пользователи домена
  Permissions 504

WARNING: Error parsing flat file b'/volumeUSB2/usbshare/backup_images4web/rdiff-backup-data/mirror_metadata.2023-11-03T15:15:37+11:00.snapshot.gz' of type <class 'rdiffbackup.meta.stdattr.AttrExtractor'> due to exception ''ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)', metadata record ignored

## More information

I made corrections to the code in the file stdattr.py, and the program began to work correctly.

 96     def _record_to_object(cls, record_string):
...
...
...
113                     # data_dict[cls._decode_mapping[field]] = data.decode('ascii')
114                     data_dict[cls._decode_mapping[field]] = data.decode('utf-8')
